// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     stream_data_record_message_schema.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayMapString(r []map[string]string, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeMapString(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayMapStringWrapper struct {
	Target *[]map[string]string
}

func (_ ArrayMapStringWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayMapStringWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayMapStringWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayMapStringWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayMapStringWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayMapStringWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayMapStringWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayMapStringWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayMapStringWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayMapStringWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayMapStringWrapper) Finalize()                        {}
func (_ ArrayMapStringWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayMapStringWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]map[string]string, 0, s)
	}
}
func (r ArrayMapStringWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayMapStringWrapper) AppendArray() types.Field {
	var v map[string]string
	v = make(map[string]string)

	*r.Target = append(*r.Target, v)
	return &MapStringWrapper{Target: &(*r.Target)[len(*r.Target)-1]}
}
