// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     stream_data_record_message_schema.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArraySqlAttributeBindingDataDto(r []SqlAttributeBindingDataDto, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeSqlAttributeBindingDataDto(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArraySqlAttributeBindingDataDtoWrapper struct {
	Target *[]SqlAttributeBindingDataDto
}

func (_ ArraySqlAttributeBindingDataDtoWrapper) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ArraySqlAttributeBindingDataDtoWrapper) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ArraySqlAttributeBindingDataDtoWrapper) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ArraySqlAttributeBindingDataDtoWrapper) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ArraySqlAttributeBindingDataDtoWrapper) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ArraySqlAttributeBindingDataDtoWrapper) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ArraySqlAttributeBindingDataDtoWrapper) SetString(v string)   { panic("Unsupported operation") }
func (_ ArraySqlAttributeBindingDataDtoWrapper) SetUnionElem(v int64) { panic("Unsupported operation") }
func (_ ArraySqlAttributeBindingDataDtoWrapper) Get(i int) types.Field {
	panic("Unsupported operation")
}
func (_ ArraySqlAttributeBindingDataDtoWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArraySqlAttributeBindingDataDtoWrapper) Finalize()        {}
func (_ ArraySqlAttributeBindingDataDtoWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r ArraySqlAttributeBindingDataDtoWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]SqlAttributeBindingDataDto, 0, s)
	}
}
func (r ArraySqlAttributeBindingDataDtoWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArraySqlAttributeBindingDataDtoWrapper) AppendArray() types.Field {
	var v SqlAttributeBindingDataDto
	v = NewSqlAttributeBindingDataDto()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
