// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     stream_data_record_message_schema.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayRecordLastValueExpresssionDTO(r []RecordLastValueExpresssionDTO, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeRecordLastValueExpresssionDTO(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayRecordLastValueExpresssionDTOWrapper struct {
	Target *[]RecordLastValueExpresssionDTO
}

func (_ ArrayRecordLastValueExpresssionDTOWrapper) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ ArrayRecordLastValueExpresssionDTOWrapper) SetInt(v int32)    { panic("Unsupported operation") }
func (_ ArrayRecordLastValueExpresssionDTOWrapper) SetLong(v int64)   { panic("Unsupported operation") }
func (_ ArrayRecordLastValueExpresssionDTOWrapper) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ ArrayRecordLastValueExpresssionDTOWrapper) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ ArrayRecordLastValueExpresssionDTOWrapper) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ ArrayRecordLastValueExpresssionDTOWrapper) SetString(v string) {
	panic("Unsupported operation")
}
func (_ ArrayRecordLastValueExpresssionDTOWrapper) SetUnionElem(v int64) {
	panic("Unsupported operation")
}
func (_ ArrayRecordLastValueExpresssionDTOWrapper) Get(i int) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayRecordLastValueExpresssionDTOWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayRecordLastValueExpresssionDTOWrapper) Finalize()        {}
func (_ ArrayRecordLastValueExpresssionDTOWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r ArrayRecordLastValueExpresssionDTOWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]RecordLastValueExpresssionDTO, 0, s)
	}
}
func (r ArrayRecordLastValueExpresssionDTOWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayRecordLastValueExpresssionDTOWrapper) AppendArray() types.Field {
	var v RecordLastValueExpresssionDTO
	v = NewRecordLastValueExpresssionDTO()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
