// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     stream_data_record_message_schema.avsc
 */
package avro

import (
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
	"io"
)

func writeMapRefValueMappingDTO(r map[string]RefValueMappingDTO, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = vm.WriteString(k, w)
		if err != nil {
			return err
		}
		err = writeRefValueMappingDTO(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type MapRefValueMappingDTOWrapper struct {
	Target *map[string]RefValueMappingDTO
	keys   []string
	values []RefValueMappingDTO
}

func (_ *MapRefValueMappingDTOWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *MapRefValueMappingDTOWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *MapRefValueMappingDTOWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *MapRefValueMappingDTOWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *MapRefValueMappingDTOWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *MapRefValueMappingDTOWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *MapRefValueMappingDTOWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ *MapRefValueMappingDTOWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *MapRefValueMappingDTOWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *MapRefValueMappingDTOWrapper) SetDefault(i int)      { panic("Unsupported operation") }

func (r *MapRefValueMappingDTOWrapper) HintSize(s int) {
	if r.keys == nil {
		r.keys = make([]string, 0, s)
		r.values = make([]RefValueMappingDTO, 0, s)
	}
}

func (r *MapRefValueMappingDTOWrapper) NullField(_ int) {
	panic("Unsupported operation")
}

func (r *MapRefValueMappingDTOWrapper) Finalize() {
	for i := range r.keys {
		(*r.Target)[r.keys[i]] = r.values[i]
	}
}

func (r *MapRefValueMappingDTOWrapper) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v RefValueMappingDTO
	v = NewRefValueMappingDTO()

	r.values = append(r.values, v)
	return &types.Record{Target: &r.values[len(r.values)-1]}
}

func (_ *MapRefValueMappingDTOWrapper) AppendArray() types.Field { panic("Unsupported operation") }
