// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     stream_data_record_message_schema.avsc
 */
package avro

import (
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
	"io"
)

func writeMapArrayUnionStringNull(r map[string][]*UnionStringNull, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = vm.WriteString(k, w)
		if err != nil {
			return err
		}
		err = writeArrayUnionStringNull(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type MapArrayUnionStringNullWrapper struct {
	Target *map[string][]*UnionStringNull
	keys   []string
	values [][]*UnionStringNull
}

func (_ *MapArrayUnionStringNullWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *MapArrayUnionStringNullWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *MapArrayUnionStringNullWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *MapArrayUnionStringNullWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *MapArrayUnionStringNullWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *MapArrayUnionStringNullWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *MapArrayUnionStringNullWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ *MapArrayUnionStringNullWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *MapArrayUnionStringNullWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *MapArrayUnionStringNullWrapper) SetDefault(i int)      { panic("Unsupported operation") }

func (r *MapArrayUnionStringNullWrapper) HintSize(s int) {
	if r.keys == nil {
		r.keys = make([]string, 0, s)
		r.values = make([][]*UnionStringNull, 0, s)
	}
}

func (r *MapArrayUnionStringNullWrapper) NullField(_ int) {
	panic("Unsupported operation")
}

func (r *MapArrayUnionStringNullWrapper) Finalize() {
	for i := range r.keys {
		(*r.Target)[r.keys[i]] = r.values[i]
	}
}

func (r *MapArrayUnionStringNullWrapper) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v []*UnionStringNull
	v = make([]*UnionStringNull, 0)

	r.values = append(r.values, v)
	return &ArrayUnionStringNullWrapper{Target: &r.values[len(r.values)-1]}
}

func (_ *MapArrayUnionStringNullWrapper) AppendArray() types.Field { panic("Unsupported operation") }
