// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     stream_data_record_message_schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullMapArrayUnionStringNullTypeEnum int

const (
	UnionNullMapArrayUnionStringNullTypeEnumMapArrayUnionStringNull UnionNullMapArrayUnionStringNullTypeEnum = 1
)

type UnionNullMapArrayUnionStringNull struct {
	Null                    *types.NullVal
	MapArrayUnionStringNull map[string][]*UnionStringNull
	UnionType               UnionNullMapArrayUnionStringNullTypeEnum
}

func writeUnionNullMapArrayUnionStringNull(r *UnionNullMapArrayUnionStringNull, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullMapArrayUnionStringNullTypeEnumMapArrayUnionStringNull:
		return writeMapArrayUnionStringNull(r.MapArrayUnionStringNull, w)
	}
	return fmt.Errorf("invalid value for *UnionNullMapArrayUnionStringNull")
}

func NewUnionNullMapArrayUnionStringNull() *UnionNullMapArrayUnionStringNull {
	return &UnionNullMapArrayUnionStringNull{}
}

func (r *UnionNullMapArrayUnionStringNull) Serialize(w io.Writer) error {
	return writeUnionNullMapArrayUnionStringNull(r, w)
}

func DeserializeUnionNullMapArrayUnionStringNull(r io.Reader) (*UnionNullMapArrayUnionStringNull, error) {
	t := NewUnionNullMapArrayUnionStringNull()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullMapArrayUnionStringNullFromSchema(r io.Reader, schema string) (*UnionNullMapArrayUnionStringNull, error) {
	t := NewUnionNullMapArrayUnionStringNull()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullMapArrayUnionStringNull) Schema() string {
	return "[\"null\",{\"type\":\"map\",\"values\":{\"items\":[\"string\",\"null\"],\"type\":\"array\"}}]"
}

func (_ *UnionNullMapArrayUnionStringNull) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullMapArrayUnionStringNull) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullMapArrayUnionStringNull) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullMapArrayUnionStringNull) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullMapArrayUnionStringNull) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullMapArrayUnionStringNull) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullMapArrayUnionStringNull) SetLong(v int64) {

	r.UnionType = (UnionNullMapArrayUnionStringNullTypeEnum)(v)
}

func (r *UnionNullMapArrayUnionStringNull) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.MapArrayUnionStringNull = make(map[string][]*UnionStringNull)
		return &MapArrayUnionStringNullWrapper{Target: (&r.MapArrayUnionStringNull)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullMapArrayUnionStringNull) NullField(i int)  { panic("Unsupported operation") }
func (_ *UnionNullMapArrayUnionStringNull) HintSize(i int)   { panic("Unsupported operation") }
func (_ *UnionNullMapArrayUnionStringNull) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullMapArrayUnionStringNull) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullMapArrayUnionStringNull) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullMapArrayUnionStringNull) Finalize()                {}

func (r *UnionNullMapArrayUnionStringNull) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullMapArrayUnionStringNullTypeEnumMapArrayUnionStringNull:
		return json.Marshal(map[string]interface{}{"map": r.MapArrayUnionStringNull})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullMapArrayUnionStringNull")
}

func (r *UnionNullMapArrayUnionStringNull) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["map"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.MapArrayUnionStringNull)
	}
	return fmt.Errorf("invalid value for *UnionNullMapArrayUnionStringNull")
}
