// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     stream_data_record_message_schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullMapRefValueMappingDTOTypeEnum int

const (
	UnionNullMapRefValueMappingDTOTypeEnumMapRefValueMappingDTO UnionNullMapRefValueMappingDTOTypeEnum = 1
)

type UnionNullMapRefValueMappingDTO struct {
	Null                  *types.NullVal
	MapRefValueMappingDTO map[string]RefValueMappingDTO
	UnionType             UnionNullMapRefValueMappingDTOTypeEnum
}

func writeUnionNullMapRefValueMappingDTO(r *UnionNullMapRefValueMappingDTO, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullMapRefValueMappingDTOTypeEnumMapRefValueMappingDTO:
		return writeMapRefValueMappingDTO(r.MapRefValueMappingDTO, w)
	}
	return fmt.Errorf("invalid value for *UnionNullMapRefValueMappingDTO")
}

func NewUnionNullMapRefValueMappingDTO() *UnionNullMapRefValueMappingDTO {
	return &UnionNullMapRefValueMappingDTO{}
}

func (r *UnionNullMapRefValueMappingDTO) Serialize(w io.Writer) error {
	return writeUnionNullMapRefValueMappingDTO(r, w)
}

func DeserializeUnionNullMapRefValueMappingDTO(r io.Reader) (*UnionNullMapRefValueMappingDTO, error) {
	t := NewUnionNullMapRefValueMappingDTO()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullMapRefValueMappingDTOFromSchema(r io.Reader, schema string) (*UnionNullMapRefValueMappingDTO, error) {
	t := NewUnionNullMapRefValueMappingDTO()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullMapRefValueMappingDTO) Schema() string {
	return "[\"null\",{\"type\":\"map\",\"values\":{\"fields\":[{\"default\":null,\"name\":\"treeNode\",\"type\":[\"null\",\"long\"]},{\"default\":null,\"name\":\"keyMappings\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]},{\"default\":false,\"name\":\"useAppliedNetworkElement\",\"type\":\"boolean\"}],\"name\":\"RefValueMappingDTO\",\"type\":\"record\"}}]"
}

func (_ *UnionNullMapRefValueMappingDTO) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullMapRefValueMappingDTO) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullMapRefValueMappingDTO) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullMapRefValueMappingDTO) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullMapRefValueMappingDTO) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullMapRefValueMappingDTO) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullMapRefValueMappingDTO) SetLong(v int64) {

	r.UnionType = (UnionNullMapRefValueMappingDTOTypeEnum)(v)
}

func (r *UnionNullMapRefValueMappingDTO) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.MapRefValueMappingDTO = make(map[string]RefValueMappingDTO)
		return &MapRefValueMappingDTOWrapper{Target: (&r.MapRefValueMappingDTO)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullMapRefValueMappingDTO) NullField(i int)  { panic("Unsupported operation") }
func (_ *UnionNullMapRefValueMappingDTO) HintSize(i int)   { panic("Unsupported operation") }
func (_ *UnionNullMapRefValueMappingDTO) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullMapRefValueMappingDTO) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullMapRefValueMappingDTO) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullMapRefValueMappingDTO) Finalize()                {}

func (r *UnionNullMapRefValueMappingDTO) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullMapRefValueMappingDTOTypeEnumMapRefValueMappingDTO:
		return json.Marshal(map[string]interface{}{"map": r.MapRefValueMappingDTO})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullMapRefValueMappingDTO")
}

func (r *UnionNullMapRefValueMappingDTO) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["map"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.MapRefValueMappingDTO)
	}
	return fmt.Errorf("invalid value for *UnionNullMapRefValueMappingDTO")
}
