// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     stream_data_record_message_schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullMapIntTypeEnum int

const (
	UnionNullMapIntTypeEnumMapInt UnionNullMapIntTypeEnum = 1
)

type UnionNullMapInt struct {
	Null      *types.NullVal
	MapInt    map[string]int32
	UnionType UnionNullMapIntTypeEnum
}

func writeUnionNullMapInt(r *UnionNullMapInt, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullMapIntTypeEnumMapInt:
		return writeMapInt(r.MapInt, w)
	}
	return fmt.Errorf("invalid value for *UnionNullMapInt")
}

func NewUnionNullMapInt() *UnionNullMapInt {
	return &UnionNullMapInt{}
}

func (r *UnionNullMapInt) Serialize(w io.Writer) error {
	return writeUnionNullMapInt(r, w)
}

func DeserializeUnionNullMapInt(r io.Reader) (*UnionNullMapInt, error) {
	t := NewUnionNullMapInt()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullMapIntFromSchema(r io.Reader, schema string) (*UnionNullMapInt, error) {
	t := NewUnionNullMapInt()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullMapInt) Schema() string {
	return "[\"null\",{\"type\":\"map\",\"values\":\"int\"}]"
}

func (_ *UnionNullMapInt) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullMapInt) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullMapInt) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullMapInt) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullMapInt) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullMapInt) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullMapInt) SetLong(v int64) {

	r.UnionType = (UnionNullMapIntTypeEnum)(v)
}

func (r *UnionNullMapInt) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.MapInt = make(map[string]int32)
		return &MapIntWrapper{Target: (&r.MapInt)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullMapInt) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullMapInt) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullMapInt) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullMapInt) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullMapInt) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullMapInt) Finalize()                        {}

func (r *UnionNullMapInt) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullMapIntTypeEnumMapInt:
		return json.Marshal(map[string]interface{}{"map": r.MapInt})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullMapInt")
}

func (r *UnionNullMapInt) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["map"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.MapInt)
	}
	return fmt.Errorf("invalid value for *UnionNullMapInt")
}
